<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_34Demo_EmpLib</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Effort.EF6" Version="2.2.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\33Demo_MyLib\33Demo_MyLib.csproj" />
  </ItemGroup>

</Project>
